In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import numpy as np
import pandas as pd


In [3]:
df= pd.read_csv("Data Set 2.csv")
df.head()

id  customer_id  location_id   channel  amount       bill_no  \
0  42877344           60          192      uber    1039  GGN001-24323   
1  35625005          134          535  takeaway    1029   DEL007-1522   
2  44397299          166          347      uber     355  DEL005-29173   
3  44405460          166          347      uber     371  DEL005-29180   
4  44717004          166          347      uber     371  DEL005-29603   

         created_on  
0  24-06-2018 00:00  
1  14-01-2018 19:21  
2  13-09-2018 13:40  
3  13-09-2018 14:33  
4  16-09-2018 12:40

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 533327 entries, 0 to 533326
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype 
---  ------       --------------   ----- 
 0   id           533327 non-null  int64 
 1   customer_id  533327 non-null  int64 
 2   location_id  533327 non-null  int64 
 3   channel      533327 non-null  object
 4   amount       533327 non-null  int64 
 5   bill_no      533327 non-null  object
 6   created_on   533327 non-null  object
dtypes: int64(4), object(3)
memory usage: 28.5+ MB


In [5]:
df.shape

(533327, 7)

In [6]:
df["created_on"] = pd.to_datetime(df["created_on"])
df.head()

id  customer_id  location_id   channel  amount       bill_no  \
0  42877344           60          192      uber    1039  GGN001-24323   
1  35625005          134          535  takeaway    1029   DEL007-1522   
2  44397299          166          347      uber     355  DEL005-29173   
3  44405460          166          347      uber     371  DEL005-29180   
4  44717004          166          347      uber     371  DEL005-29603   

           created_on  
0 2018-06-24 00:00:00  
1 2018-01-14 19:21:00  
2 2018-09-13 13:40:00  
3 2018-09-13 14:33:00  
4 2018-09-16 12:40:00

In [7]:
df["year"] = df["created_on"].dt.year
df["month"] = df["created_on"].dt.month


In [8]:
df.head()



id  customer_id  location_id   channel  amount       bill_no  \
0  42877344           60          192      uber    1039  GGN001-24323   
1  35625005          134          535  takeaway    1029   DEL007-1522   
2  44397299          166          347      uber     355  DEL005-29173   
3  44405460          166          347      uber     371  DEL005-29180   
4  44717004          166          347      uber     371  DEL005-29603   

           created_on  year  month  
0 2018-06-24 00:00:00  2018      6  
1 2018-01-14 19:21:00  2018      1  
2 2018-09-13 13:40:00  2018      9  
3 2018-09-13 14:33:00  2018      9  
4 2018-09-16 12:40:00  2018      9

In [9]:
df.drop("created_on",1,inplace=True)

In [10]:
df.head()

id  customer_id  location_id   channel  amount       bill_no  year  \
0  42877344           60          192      uber    1039  GGN001-24323  2018   
1  35625005          134          535  takeaway    1029   DEL007-1522  2018   
2  44397299          166          347      uber     355  DEL005-29173  2018   
3  44405460          166          347      uber     371  DEL005-29180  2018   
4  44717004          166          347      uber     371  DEL005-29603  2018   

   month  
0      6  
1      1  
2      9  
3      9  
4      9

In [11]:
df["year"].value_counts()

2018    383076
2019    150251
Name: year, dtype: int64

In [12]:
df["month"].value_counts()

3     71603
2     58183
1     54457
11    47533
9     43257
10    42097
12    39074
7     38930
6     37788
8     34308
5     34068
4     32029
Name: month, dtype: int64

# 1.Sheet name : Overall.

#### Revenue every month

In [13]:
Revenue = df.groupby(by="month").sum()["amount"]
Revenue 

month
1     31684629
2     30929668
3     35029989
4     17950133
5     19198618
6     21381004
7     22101857
8     19479356
9     21234378
10    24061725
11    27409901
12    23615178
Name: amount, dtype: int64

#### fetching the values and reshaping it for the final output dataframe

In [14]:
Revenue = Revenue.values.reshape((1,12))
Revenue

array([[31684629, 30929668, 35029989, 17950133, 19198618, 21381004,
        22101857, 19479356, 21234378, 24061725, 27409901, 23615178]],
      dtype=int64)

#### order every month

In [15]:
Orders = df.groupby(by="month").count()["id"]
Orders

month
1     54457
2     58183
3     71603
4     32029
5     34068
6     37788
7     38930
8     34308
9     43257
10    42097
11    47533
12    39074
Name: id, dtype: int64

In [16]:
Orders = Orders.values.reshape((1,12))
Orders

array([[54457, 58183, 71603, 32029, 34068, 37788, 38930, 34308, 43257,
        42097, 47533, 39074]], dtype=int64)

#### Unique customer every month

In [17]:
Customers =  df.groupby(["month"]).nunique()["customer_id"]
Customers

month
1     40623
2     44205
3     52429
4     24692
5     26332
6     29466
7     30525
8     27352
9     33120
10    32179
11    35788
12    30315
Name: customer_id, dtype: int64

In [18]:
Customers = Customers.values.reshape((1,12))
Customers

array([[40623, 44205, 52429, 24692, 26332, 29466, 30525, 27352, 33120,
        32179, 35788, 30315]], dtype=int64)

### New Customer every month

In [19]:
# if the customer_id is again shaowing with different product_id then the customer will be an old customer
# bascially if the customer_id count is one then it should be an new cutomers

In [20]:
df["new_customer"] =df["customer_id"].apply(lambda x:1 if x not in df["customer_id"] else 0)

In [21]:
df.head(10)

id  customer_id  location_id   channel  amount       bill_no  year  \
0  42877344           60          192      uber    1039  GGN001-24323  2018   
1  35625005          134          535  takeaway    1029   DEL007-1522  2018   
2  44397299          166          347      uber     355  DEL005-29173  2018   
3  44405460          166          347      uber     371  DEL005-29180  2018   
4  44717004          166          347      uber     371  DEL005-29603  2018   
5  58101623          166          347      uber     252  DEL005-50335  2019   
6  58550796          166          347      uber     252  DEL005-51476  2019   
7  36018577          180         4593  takeaway      60   GGN007-1266  2018   
8  38731245          180          270  takeaway     372  DEL001-15243  2018   
9  43252192          180          192  takeaway     450  GGN001-30768  2018   

   month  new_customer  
0      6             0  
1      1             0  
2      9             0  
3      9             0  
4      9             0  
5      2             0  
6      2             0  
7      1             0  
8     12             0  
9      4             0

In [22]:
New_customers = df.groupby(["month"]).sum()["new_customer"]
New_customers

month
1     43442
2     47470
3     59760
4     25029
5     27018
6     30346
7     31837
8     27692
9     36195
10    35968
11    40729
12    32404
Name: new_customer, dtype: int64

In [23]:
New_customers = New_customers.values.reshape((1,12))
New_customers

array([[43442, 47470, 59760, 25029, 27018, 30346, 31837, 27692, 36195,
        35968, 40729, 32404]], dtype=int64)

### Repeated customers

***Customers with order more than one are repeated customers***

In [24]:
df["repeated_customer"] =df["customer_id"].apply(lambda x:1 if x in df["customer_id"] else 0)

In [25]:
Repeated_customers = df.groupby(["month"]).sum()["repeated_customer"]
Repeated_customers

month
1     11015
2     10713
3     11843
4      7000
5      7050
6      7442
7      7093
8      6616
9      7062
10     6129
11     6804
12     6670
Name: repeated_customer, dtype: int64

In [26]:
Repeated_customers = Repeated_customers.values.reshape((1,12))
Repeated_customers

array([[11015, 10713, 11843,  7000,  7050,  7442,  7093,  6616,  7062,
         6129,  6804,  6670]], dtype=int64)

### Frequency

In [27]:
frequency0 = Orders/Customers
frequency0 = frequency0.reshape((-1)) # data was was not in one dimensional that's why i did this

In [28]:
frequency0 = pd.Series(frequency0)  # for taking the values of the data first convert it into the series

In [29]:
# reshaping it for the final dataframe
frequency0 = frequency0.values.reshape((1,12))
frequency0

array([[1.340546  , 1.31620857, 1.36571363, 1.29714077, 1.29378703,
        1.2824272 , 1.27534808, 1.25431413, 1.30606884, 1.30821343,
        1.32818263, 1.28893287]])

# Final Dataframe

In [30]:
Overall= pd.DataFrame(columns=["month1","month2","month3","month4","month5","month6","month7","month8","month9","month10","month11","month12"],
                      index=["Revenue","Orders","Customers","New Customers","Repeated Customers","Frequnency"])

Overall.iloc[0:1,:] = Revenue
Overall.iloc[1:2,:] = Orders
Overall.iloc[2:3,:] = Customers
Overall.iloc[3:4,:] = New_customers
Overall.iloc[4:5,:] = Repeated_customers
Overall.iloc[5:6,:] = frequency0

In [31]:
Overall

month1    month2    month3    month4    month5  \
Revenue             31684629  30929668  35029989  17950133  19198618   
Orders                 54457     58183     71603     32029     34068   
Customers              40623     44205     52429     24692     26332   
New Customers          43442     47470     59760     25029     27018   
Repeated Customers     11015     10713     11843      7000      7050   
Frequnency          1.340546  1.316209  1.365714  1.297141  1.293787   

                      month6    month7    month8    month9   month10  \
Revenue             21381004  22101857  19479356  21234378  24061725   
Orders                 37788     38930     34308     43257     42097   
Customers              29466     30525     27352     33120     32179   
New Customers          30346     31837     27692     36195     35968   
Repeated Customers      7442      7093      6616      7062      6129   
Frequnency          1.282427  1.275348  1.254314  1.306069  1.308213   

                     month11   month12  
Revenue             27409901  23615178  
Orders                 47533     39074  
Customers              35788     30315  
New Customers          40729     32404  
Repeated Customers      6804      6670  
Frequnency          1.328183  1.288933

# 2.Sheet Two : Location one

# <font color="Red"> <i>LOCATION WISE  ->  Location one</i></font>

## Taking one location one

In [32]:
location_one = df["location_id"][0]
location_one

192

In [33]:
location_one_data = df[df["location_id"]==location_one]
location_one_data

id  customer_id  location_id   channel  amount       bill_no  \
0       42877344           60          192      uber    1039  GGN001-24323   
9       43252192          180          192  takeaway     450  GGN001-30768   
10      50301882          180          192      call     498  GGN001-45567   
20      46912884          734          192    zomato    1032  GGN001-49633   
21      38629641          790          192  takeaway    1365   GGN001-6908   
...          ...          ...          ...       ...     ...           ...   
533288  63920261     11655151          192    zomato      99  GGN001-88287   
533298  63920324     11655161          192    zomato     209  GGN001-88145   
533303  63920393     11655165          192    zomato     129  GGN001-88151   
533308  63920449     11655170          192      uber     305  GGN001-88239   
533325  63920586     11655187          192      uber     252  GGN001-88302   

        year  month  new_customer  repeated_customer  
0       2018      6             0                  1  
9       2018      4             0                  1  
10      2018     10             0                  1  
20      2018      6             0                  1  
21      2018      2             0                  1  
...      ...    ...           ...                ...  
533288  2019     10             1                  0  
533298  2019     10             1                  0  
533303  2019     10             1                  0  
533308  2019     10             1                  0  
533325  2019     10             1                  0  

[58181 rows x 10 columns]

### Revenue for location one

In [34]:
Revenue1=location_one_data.groupby("month").sum()["amount"]
Revenue1

month
1     2853294
2     3096092
3     3407309
4     1818778
5     1976465
6     2127114
7     2400093
8     2109800
9     2379890
10    2804921
11    3214703
12    2141932
Name: amount, dtype: int64

Reshaping for the final dataset

In [35]:
Revenue1 = Revenue1.values.reshape((1,12))
Revenue1

array([[2853294, 3096092, 3407309, 1818778, 1976465, 2127114, 2400093,
        2109800, 2379890, 2804921, 3214703, 2141932]], dtype=int64)

### Orders for location one

In [36]:
Orders1 = location_one_data.groupby(by="month").count()["id"]
Orders1

month
1     5072
2     6116
3     7499
4     3711
5     4060
6     3766
7     4306
8     3796
9     4364
10    5423
11    5919
12    4149
Name: id, dtype: int64

In [37]:
# reshaping
Orders1 = Orders1.values.reshape((1,12))
Orders1

array([[5072, 6116, 7499, 3711, 4060, 3766, 4306, 3796, 4364, 5423, 5919,
        4149]], dtype=int64)

### Unique Customers for location one

In [38]:
Customers1 =location_one_data.groupby("month").nunique()["customer_id"]
Customers1

month
1     4262
2     5091
3     6146
4     3134
5     3364
6     3302
7     3690
8     3304
9     3701
10    4322
11    4755
12    3492
Name: customer_id, dtype: int64

In [39]:
# reshaping
Customers1 = Customers1.values.reshape((1,12))
Customers1


array([[4262, 5091, 6146, 3134, 3364, 3302, 3690, 3304, 3701, 4322, 4755,
        3492]], dtype=int64)

### New customers for location one

In [40]:
location_one_data.head()

id  customer_id  location_id   channel  amount       bill_no  year  \
0   42877344           60          192      uber    1039  GGN001-24323  2018   
9   43252192          180          192  takeaway     450  GGN001-30768  2018   
10  50301882          180          192      call     498  GGN001-45567  2018   
20  46912884          734          192    zomato    1032  GGN001-49633  2018   
21  38629641          790          192  takeaway    1365   GGN001-6908  2018   

    month  new_customer  repeated_customer  
0       6             0                  1  
9       4             0                  1  
10     10             0                  1  
20      6             0                  1  
21      2             0                  1

In [41]:
New_customers1 = location_one_data.groupby(["month"]).sum()["new_customer"]
New_customers1

month
1     3726
2     4674
3     5940
4     2768
5     2979
6     2791
7     3316
8     2870
9     3404
10    4482
11    4830
12    3266
Name: new_customer, dtype: int64

In [42]:
# reshaping
New_customers1 = New_customers1.values.reshape((1,12))
New_customers1

array([[3726, 4674, 5940, 2768, 2979, 2791, 3316, 2870, 3404, 4482, 4830,
        3266]], dtype=int64)

### Repeated customers fir location one

***Customers with order more than one are repeated customers***

In [43]:
location_one_data.head()

id  customer_id  location_id   channel  amount       bill_no  year  \
0   42877344           60          192      uber    1039  GGN001-24323  2018   
9   43252192          180          192  takeaway     450  GGN001-30768  2018   
10  50301882          180          192      call     498  GGN001-45567  2018   
20  46912884          734          192    zomato    1032  GGN001-49633  2018   
21  38629641          790          192  takeaway    1365   GGN001-6908  2018   

    month  new_customer  repeated_customer  
0       6             0                  1  
9       4             0                  1  
10     10             0                  1  
20      6             0                  1  
21      2             0                  1

In [44]:
Repeated_customers1 = location_one_data.groupby(["month"]).sum()["repeated_customer"]
Repeated_customers1

month
1     1346
2     1442
3     1559
4      943
5     1081
6      975
7      990
8      926
9      960
10     941
11    1089
12     883
Name: repeated_customer, dtype: int64

In [45]:
# reshaping
Repeated_customers1 = Repeated_customers1.values.reshape((1,12))
Repeated_customers1

array([[1346, 1442, 1559,  943, 1081,  975,  990,  926,  960,  941, 1089,
         883]], dtype=int64)

### Frequency for location one 

In [46]:
frequency1 = Orders1/Customers1
frequency1

array([[1.19005162, 1.20133569, 1.22014318, 1.18410976, 1.20689655,
        1.1405209 , 1.16693767, 1.14891041, 1.17914077, 1.25474317,
        1.24479495, 1.18814433]])

In [47]:
frequency1.shape

(1, 12)

In [48]:
frequency1 = frequency1.reshape((-1))
frequency1 = pd.Series(frequency1)
frequency1.shape

(12,)

In [49]:
# reshaping
frequency1= frequency1.values.reshape((1,12))
frequency1

array([[1.19005162, 1.20133569, 1.22014318, 1.18410976, 1.20689655,
        1.1405209 , 1.16693767, 1.14891041, 1.17914077, 1.25474317,
        1.24479495, 1.18814433]])

## Dataframe for location one

In [50]:
location1 = location1= pd.DataFrame(columns=["month1","month2","month3","month4","month5","month6","month7","month8","month9","month10","month11","month12"],
                      index=["Revenue","Orders","Customers","New Customers","Repeated Customers","Frequnency"])

location1.iloc[0:1,:] = Revenue1
location1.iloc[1:2,:] = Orders1
location1.iloc[2:3,:] = Customers1
location1.iloc[3:4,:] = New_customers1
location1.iloc[4:5,:] = Repeated_customers1
location1.iloc[5:6,:] = frequency1

In [51]:
location1

month1    month2    month3   month4    month5    month6  \
Revenue              2853294   3096092   3407309  1818778   1976465   2127114   
Orders                  5072      6116      7499     3711      4060      3766   
Customers               4262      5091      6146     3134      3364      3302   
New Customers           3726      4674      5940     2768      2979      2791   
Repeated Customers      1346      1442      1559      943      1081       975   
Frequnency          1.190052  1.201336  1.220143  1.18411  1.206897  1.140521   

                      month7   month8    month9   month10   month11   month12  
Revenue              2400093  2109800   2379890   2804921   3214703   2141932  
Orders                  4306     3796      4364      5423      5919      4149  
Customers               3690     3304      3701      4322      4755      3492  
New Customers           3316     2870      3404      4482      4830      3266  
Repeated Customers       990      926       960       941      1089       883  
Frequnency          1.166938  1.14891  1.179141  1.254743  1.244795  1.188144

# 3.Sheet name :Location Two.

# Let's do the same for <font color="red">LOCATION TWO</font>

In [52]:
# taking location two
location2 = df["location_id"][1]
location2

535

In [53]:
location_two_data = df[df["location_id"]==location2]
location_two_data

id  customer_id  location_id    channel  amount       bill_no  \
1       35625005          134          535   takeaway    1029   DEL007-1522   
19      39746591          726          535     outlet    1489   DEL007-4839   
22      58058872          854          535    dine in     359  DEL007-25861   
46      36824556         2107          535  foodpanda     372   DEL007-2478   
64      50269530         2589          535     zomato    1181  DEL007-14494   
...          ...          ...          ...        ...     ...           ...   
533175  63919459     11655046          535     zomato     203  DEL007-31194   
533182  63919504     11655052          535       uber     504  DEL007-31241   
533198  63919604     11655067          535       uber     305  DEL007-31214   
533252  63920029     11655116          535     zomato     129  DEL007-31230   
533313  63920513     11655175          535     zomato     185  DEL007-31265   

        year  month  new_customer  repeated_customer  
1       2018      1             0                  1  
19      2018      3             0                  1  
22      2019      2             0                  1  
46      2018      8             0                  1  
64      2018      6             0                  1  
...      ...    ...           ...                ...  
533175  2019     10             1                  0  
533182  2019     10             1                  0  
533198  2019     10             1                  0  
533252  2019     10             1                  0  
533313  2019     10             1                  0  

[16968 rows x 10 columns]

In [54]:
# checking the shape
location_two_data.shape

(16968, 10)

## Revenue location 2

In [55]:

Revenue2=location_two_data.groupby("month").sum()["amount"]

# reshaping the data for final dataframe
Revenue2 = Revenue2.values.reshape((1,12))
Revenue2

array([[ 970870,  947606, 1074114,  573780,  617699,  656355,  715230,
         573941,  387696,  900017,  986563,  591205]], dtype=int64)

## Orders location 2

In [56]:
Orders2 = location_two_data.groupby(by="month").count()["id"]
# reshaping
Orders2 = Orders2.values.reshape((1,12))
Orders2

array([[1710, 1828, 2223,  945, 1090, 1264, 1350, 1099,  759, 1675, 1885,
        1140]], dtype=int64)

## unique customer location 2

In [57]:
Customers2 =location_two_data.groupby("month").nunique()["customer_id"]
# reshaping
Customers2 = Customers2.values.reshape((1,12))
Customers2


array([[1428, 1550, 1764,  823,  945, 1113, 1165,  995,  711, 1320, 1551,
         996]], dtype=int64)

## New customer location 2

In [58]:
New_customers2 = location_two_data.groupby(["month"]).sum()["new_customer"]
# reshaping
New_customers2 = New_customers2.values.reshape((1,12))
New_customers2


array([[1451, 1557, 1890,  778,  898, 1061, 1164,  903,  644, 1513, 1695,
         941]], dtype=int64)

## Repeated customer location 2

In [59]:
Repeated_customers2 = location_two_data.groupby(["month"]).sum()["repeated_customer"]
# reshaping
Repeated_customers2 = Repeated_customers2.values.reshape((1,12))
Repeated_customers2


array([[259, 271, 333, 167, 192, 203, 186, 196, 115, 162, 190, 199]],
      dtype=int64)

## frequency for location 2

In [60]:
frequency2 = Orders2/Customers
# reshoping and converting to series to get the values from the series
frequency2 = frequency2.reshape((-1))
frequency2 = pd.Series(frequency2)

# reshaping for the final dataframe
frequency2= frequency2.values.reshape((1,12))
frequency2


array([[0.04209438, 0.04135279, 0.0424002 , 0.0382715 , 0.0413945 ,
        0.0428969 , 0.04422604, 0.04017988, 0.02291667, 0.05205258,
        0.05267129, 0.03760515]])

# Datafram for the location two 

In [61]:
location2 = location2= pd.DataFrame(columns=["month1","month2","month3","month4","month5","month6","month7","month8","month9","month10","month11","month12"],
                      index=["Revenue","Orders","Customers","New Customers","Repeated Customers","Frequnency"])

location2.iloc[0:1,:] = Revenue2
location2.iloc[1:2,:] = Orders2
location2.iloc[2:3,:] = Customers2
location2.iloc[3:4,:] = New_customers2
location2.iloc[4:5,:] = Repeated_customers2
location2.iloc[5:6,:] = frequency2

In [62]:
location2

month1    month2   month3    month4    month5    month6  \
Revenue               970870    947606  1074114    573780    617699    656355   
Orders                  1710      1828     2223       945      1090      1264   
Customers               1428      1550     1764       823       945      1113   
New Customers           1451      1557     1890       778       898      1061   
Repeated Customers       259       271      333       167       192       203   
Frequnency          0.042094  0.041353   0.0424  0.038272  0.041395  0.042897   

                      month7   month8    month9   month10   month11   month12  
Revenue               715230   573941    387696    900017    986563    591205  
Orders                  1350     1099       759      1675      1885      1140  
Customers               1165      995       711      1320      1551       996  
New Customers           1164      903       644      1513      1695       941  
Repeated Customers       186      196       115       162       190       199  
Frequnency          0.044226  0.04018  0.022917  0.052053  0.052671  0.037605

In [63]:
with pd.ExcelWriter('final3.xlsx') as writer1:
    Overall.to_excel(writer1, sheet_name = 'Overall')
    location1.to_excel(writer1, sheet_name = 'location1')
    location2.to_excel(writer1, sheet_name = 'location2')

# But the problem is dataset have 33 location
## for doing manually it will take lot of time..
## so for this have to make one function


In [64]:
def location_wise(df,location_id):
        df = df[df["location_id"]==location_id]
        #revenue
        Revenue = df.groupby("month").sum()["amount"]
        Revenue = Revenue.values.reshape((1,12))
        
        #order
        Orders = df.groupby(by="month").count()["id"]
        Orders = Orders.values.reshape((1,12))
        
        #uniques customers
        Customers =df.groupby("month").nunique()["customer_id"]
        Customers =Customers.values.reshape((1,12))
        
        #new customers
        New_customers = df.groupby(["month"]).sum()["new_customer"]
        New_customers = New_customers.values.reshape((1,12))
       
        #repeated customers
        Repeated_customers = df.groupby(["month"]).sum()["repeated_customer"]
        Repeated_customers = Repeated_customers.values.reshape((1,12))
        
        #frequnecy
        frequency = Orders/Customers
        # reshoping and converting to series to get the values from the series
        frequency = frequency.reshape((-1))
        frequency = pd.Series(frequency)
        # reshaping for the final dataframe
        frequency= frequency.values.reshape((1,12))
        
        location = pd.DataFrame(columns=["month1","month2","month3","month4","month5","month6","month7","month8","month9","month10","month11","month12"],
                      index=["Revenue","Orders","Customers","New Customers","Repeated Customers","Frequnency"])

        location.iloc[0:1,:] = Revenue
        location.iloc[1:2,:] = Orders
        location.iloc[2:3,:] = Customers
        location.iloc[3:4,:] = New_customers
        location.iloc[4:5,:] = Repeated_customers
        location.iloc[5:6,:] = frequency
        
        return location
    
    

In [65]:
with pd.ExcelWriter('final5.xlsx') as writer1:
    Overall.to_excel(writer1, sheet_name = 'Overall')
    for i in range(df["location_id"].nunique()):
        location_wise(df,df["location_id"][i]).to_excel(writer1, sheet_name =f"location {i}")
    

PermissionError: [Errno 13] Permission denied: 'final5.xlsx'